# Docker profile (production via docker-compose)
spring.datasource.url=jdbc:postgresql://db:5432/vamo
spring.datasource.username=vamo_user
spring.datasource.password=vamo_pass

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

logging.level.root=INFO
