# Local development profile (IDE)
spring.datasource.url=jdbc:postgresql://localhost:5432/vamo
spring.datasource.username=vamo_user
spring.datasource.password=vamo_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.vamo=INFO
